name: complexnetworks
dependencies:
  - python==3.13.11
  - numpy=2.3.5
  - pandas==2.3.3
  - jupyter==1.1.1
  - matplotlib==3.10.7
  - scikit-learn==1.7.2
  - statsmodels==0.14.6
  - pycairo==1.23.0
  - seaborn==0.13.2
  - pip==25.3
  - gensim==4.4.0
  - pip:
    - igraph==0.11.9
    - powerlaw==1.5
    - umap-learn==0.5.8
    - partition-igraph==0.0.7
    - fastnode2vec==0.0.7
    - hypernetx==2.4.0
    - vectorizers==0.2.2
    - scikit-network==0.33.5
    - hdbscan==0.8.41
    - xgi==0.10
    - plotly==6.5.0
    - arrow==1.4.0
    - xgboost==3.1.2
    - abcd-graph==0.4.1
    - bayesian-optimization==1.5.1
    
    
    
    
    
    
    
    
